spin_manifest_version = 2

[application]
name = "spin-docs"
version = "0.1.0"
description = "Spin website running on... Spin."
authors = ["Spin Maintainers <spin@cncf.io>"]

[application.trigger.http]
base = "/"

[[trigger.http]]
id = "trigger-bartholomew"
component = "bartholomew"
route = "/..."

[[trigger.http]]
id = "trigger-fileserver-static"
component = "fileserver-static"
route = "/static/..."

[[trigger.http]]
id = "trigger-fileserver-downloads"
component = "fileserver-downloads"
route = "/downloads/..."

[[trigger.http]]
id = "trigger-hub-fileserver-static"
component = "hub-fileserver-static"
route = "/hub/..."

[[trigger.http]]
id = "trigger-spin-version-proxy"
component = "spin-version-proxy"
route = "/:page"

[[trigger.http]]
id = "trigger-bartholomew-spin-v1"
component = "bartholomew-spin-v1"
route = "/spin/v1/..."

[[trigger.http]]
id = "trigger-bartholomew-spin-v2"
component = "bartholomew-spin-v2"
route = "/spin/v2/..."

[[trigger.http]]
id = "trigger-bartholomew-spin-v3"
component = "bartholomew-spin-v3"
route = "/spin/v3/..."

[[trigger.http]]
id = "trigger-well-known"
component = "well-known"
route = "/.well-known/..."

[component.well-known]
source = "modules/spin_static_fs.wasm"
files = [{ source = "well-known/", destination = "/" }]

[component.bartholomew]
# Using build from bartholomew main
source = "modules/bartholomew.wasm"
environment = { PREVIEW_MODE = "0" }
files = ["content/**/*", "templates/*", "scripts/*", "config/*", "shortcodes/*"]

[component.bartholomew.build]
command = "npm run build-index && npm run build-hub-index"
watch = ["content/**/*", "templates/*"]

[component.fileserver-static]
source = "modules/spin_static_fs.wasm"
files = [{ source = "static/", destination = "/" }]
[component.fileserver-static.build]
command = ["npm run bundle-scripts-ci"]

[component.fileserver-downloads]
source = "modules/spin_static_fs.wasm"
files = [{ source = "downloads/", destination = "/" }]

[component.hub-fileserver-static]
source = { url = "https://github.com/spinframework/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
environment = { FALLBACK_PATH = "./index.html" }
files = [{ source = "spin-up-hub/dist/", destination = "/" }]

[component.hub-fileserver-static.build]
command = "npm run build"
workdir = "spin-up-hub"

# Component to give us clean versioned URLs for spin from the root
[component.spin-version-proxy]
source = "modules/spin-redirecter.wasm"
variables = { latest_spin_version = "v3" }
files = ["spin-redirect.json"]
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["http://self"]
# Need to modify action to get the js2wasm plugin
# [component.build]
# workdir = "spin-redirecter"
# command = "npm install && npm run build"

[component.bartholomew-spin-v1]
# Using build from bartholomew main
source = "modules/bartholomew.wasm"
environment = { PREVIEW_MODE = "0" }
files = ["content/**/*", "templates/*", "scripts/*", "config/*", "shortcodes/*"]

[component.bartholomew-spin-v1.build]
command = "npm run build-index && npm run build-hub-index"
watch = ["content/**/*", "templates/*"]

[component.bartholomew-spin-v2]
# Using build from bartholomew main
source = "modules/bartholomew.wasm"
environment = { PREVIEW_MODE = "0" }
files = ["content/**/*", "templates/*", "scripts/*", "config/*", "shortcodes/*"]

[component.bartholomew-spin-v2.build]
command = "npm run build-index && npm run build-hub-index"
watch = ["content/**/*", "templates/*"]

[component.bartholomew-spin-v3]
# Using build from bartholomew main
source = "modules/bartholomew.wasm"
environment = { PREVIEW_MODE = "0" }
files = ["content/**/*", "templates/*", "scripts/*", "config/*", "shortcodes/*"]

[[trigger.http]]
id = "trigger-redirect-kubernetes"
component = "redirect-kubernetes"
route = "/kubernetes"

[component.redirect-kubernetes]
source = "modules/redirect.wasm"
environment = { DESTINATION = "/deploying", STATUSCODE = "301" }
